process.env.APEX_CAPITAL_SELF_CHECK = "1";

import "../lib/dailyLoop/capitalDecision";
import { runCapitalProjectionSelfCheck } from "../lib/dailyLoop/capitalProjection";
import { runCapitalFinalStateSelfCheck } from "../lib/dailyLoop/capitalFinalState";
import { runCapitalDecisionLockSelfCheck } from "../lib/dailyLoop/capitalDecisionLock";
import { runCapitalMarginSelfCheck } from "../lib/dailyLoop/capitalMargin";
import { runTodaySurfaceSelfCheck } from "../lib/dailyLoop/todaySurface";
import { runZerodhaFundsSelfCheck } from "../lib/broker/zerodhaFunds";
import { runKiteDayPnlSelfCheck } from "../services/brokers/zerodha";
import { runPortfolioApiPnlFieldSelfCheck } from "../services/portfolio/format";
import { runCommitmentSelfCheck } from "../lib/dailyLoop/disciplineCommitment";
import { runDisciplineHistoryMergeSelfCheck } from "../lib/dailyLoop/disciplineHistoryMerge";
import { runTradingDateSelfCheck } from "../lib/dailyLoop/disciplineDates";
import { runDisciplineStatusSelfCheck } from "../lib/dailyLoop/disciplineStreak";
import { runBrokerStepStateSelfCheck } from "../lib/dailyLoop/brokerStepState";
import { runMarketSessionSelfCheck } from "../lib/broker/marketSession";
import { runKiteOrderProxySelfCheck } from "../lib/broker/kiteOrderProxy";
import { runOpenMonitorEntrySelfCheck } from "../services/monitor/openPositions";
import { runTradeExecutionErrorSelfCheck } from "../lib/api/clientFetch";
import { runWeeklyReviewSelfCheck } from "../lib/dailyLoop/weeklyReview";
import { runTradeFillSelfCheck } from "../services/trade/logTradeFill";
import { runSyncKiteBrokerFillSelfCheck } from "../services/trade/syncKiteBrokerFill";
import { runSyncBrokerActivitySelfCheck } from "../services/trade/syncBrokerActivity";
import { runAutoTradeSelfCheck } from "../services/trade/autoExecute";
import { runLoggerSelfCheck } from "../lib/logging/logger";
import { runMorningBriefSelfCheck } from "../services/brief/assembleMorningBrief";
import { runProjectVerdictSelfCheck } from "../lib/dailyLoop/projectVerdict";
import { runAllocationPolicySelfCheck } from "../services/portfolio/allocationPolicy";
import { runHoldingHealthSelfCheck } from "../services/portfolio/holdingHealth";
import { runDisciplineScoreSelfCheck } from "../services/review/disciplineScore";
import { runReceiptSelfCheck } from "../services/receipts/persistReceipt";
import { runResearchSummarySelfCheck } from "../services/research/assembleResearchSummary";
import { runAlphaAiBridgeSelfCheck } from "../services/research/alphaAiBridge";
import { runYouSnapshotSelfCheck } from "../services/you/assembleYouSnapshot";
import { runPlannedVsActualSelfCheck } from "../services/review/plannedVsActual";
import { runMonthlyDoctorSelfCheck } from "../services/review/assembleMonthlyDoctor";
import { runAskAnswerSelfCheck } from "../services/ask/assembleAskAnswer";
import { runReceiptExportSelfCheck } from "../services/receipts/exportReceiptMarkdown";
import { runMonthlyDoctorExportSelfCheck } from "../services/review/exportMonthlyDoctorMarkdown";
import { runMonthlyTrendsSelfCheck } from "../services/review/buildMonthlyTrends";
import { runQuarterlyReviewSelfCheck } from "../services/review/assembleQuarterlyReview";
import { runReviewCadenceSelfCheck } from "../services/review/assembleReviewCadence";
import { runReviewDigestSelfCheck } from "../services/review/reviewDigest";
import { runPortfolioAskSelfCheck } from "../services/ask/assemblePortfolioAskAnswer";
import { runInvestorDnaSelfCheck } from "../services/you/assembleInvestorDna";
import { runNewCapitalSelfCheck } from "../services/capital/newCapitalWorkflow";
import { runThesisRepositorySelfCheck } from "../services/thesis/thesisRepository";
import { runInvestmentBookExportSelfCheck } from "../services/thesis/exportInvestmentBook";
import { runSendReviewDigestSelfCheck } from "../services/review/sendReviewDigest";
import { runMacroAskSelfCheck } from "../services/ask/assembleMacroAskAnswer";
import { runContextualLessonSelfCheck } from "../services/learning/assembleContextualLesson";
import { runThesisInvalidationSelfCheck } from "../services/thesis/evaluateThesisInvalidation";
import { runReviewDigestCronSelfCheck } from "../services/review/runReviewDigestCron";
import { runParseInvalidationRuleSelfCheck } from "../services/thesis/parseInvalidationRule";
import { runDisciplineTrendsSelfCheck } from "../services/review/buildDisciplineTrends";
import { runPortfolioHealthSummarySelfCheck } from "../services/portfolio/buildPortfolioHealthSummary";

runCapitalProjectionSelfCheck();
runCapitalFinalStateSelfCheck();
runCapitalDecisionLockSelfCheck();
runCapitalMarginSelfCheck();
runTodaySurfaceSelfCheck();
runZerodhaFundsSelfCheck();
runKiteDayPnlSelfCheck();
runPortfolioApiPnlFieldSelfCheck();
runCommitmentSelfCheck();
runDisciplineHistoryMergeSelfCheck();
runTradingDateSelfCheck();
runDisciplineStatusSelfCheck();
runBrokerStepStateSelfCheck();
runMarketSessionSelfCheck();
runKiteOrderProxySelfCheck();
runOpenMonitorEntrySelfCheck();
runTradeExecutionErrorSelfCheck();
runWeeklyReviewSelfCheck();
runTradeFillSelfCheck();
runSyncKiteBrokerFillSelfCheck();
runSyncBrokerActivitySelfCheck();
runAutoTradeSelfCheck();
runLoggerSelfCheck();
runMorningBriefSelfCheck();
runProjectVerdictSelfCheck();
runAllocationPolicySelfCheck();
runHoldingHealthSelfCheck();
runDisciplineScoreSelfCheck();
runReceiptSelfCheck();
runResearchSummarySelfCheck();
runAlphaAiBridgeSelfCheck();
runYouSnapshotSelfCheck();
runPlannedVsActualSelfCheck();
runMonthlyDoctorSelfCheck();
runAskAnswerSelfCheck();
runReceiptExportSelfCheck();
runMonthlyDoctorExportSelfCheck();
runMonthlyTrendsSelfCheck();
runQuarterlyReviewSelfCheck();
runReviewCadenceSelfCheck();
runReviewDigestSelfCheck();
runPortfolioAskSelfCheck();
runInvestorDnaSelfCheck();
runNewCapitalSelfCheck();
runThesisRepositorySelfCheck();
runInvestmentBookExportSelfCheck();
runSendReviewDigestSelfCheck();
runMacroAskSelfCheck();
runContextualLessonSelfCheck();
runThesisInvalidationSelfCheck();
runReviewDigestCronSelfCheck();
runParseInvalidationRuleSelfCheck();
runDisciplineTrendsSelfCheck();
runPortfolioHealthSummarySelfCheck();
