process.env.APEX_CAPITAL_SELF_CHECK = "1";

import "../lib/dailyLoop/capitalDecision";
import { runCapitalProjectionSelfCheck } from "../lib/dailyLoop/capitalProjection";
import { runCapitalFinalStateSelfCheck } from "../lib/dailyLoop/capitalFinalState";
import { runCapitalDecisionLockSelfCheck } from "../lib/dailyLoop/capitalDecisionLock";
import { runCapitalMarginSelfCheck } from "../lib/dailyLoop/capitalMargin";
import { runTodaySurfaceSelfCheck } from "../lib/dailyLoop/todaySurface";
import { runZerodhaFundsSelfCheck } from "../lib/broker/zerodhaFunds";
import { runCommitmentSelfCheck } from "../lib/dailyLoop/disciplineCommitment";
import { runDisciplineHistoryMergeSelfCheck } from "../lib/dailyLoop/disciplineHistoryMerge";
import { runTradingDateSelfCheck } from "../lib/dailyLoop/disciplineDates";
import { runDisciplineStatusSelfCheck } from "../lib/dailyLoop/disciplineStreak";
import { runBrokerStepStateSelfCheck } from "../lib/dailyLoop/brokerStepState";
import { runMarketSessionSelfCheck } from "../lib/broker/marketSession";
import { runTradeExecutionErrorSelfCheck } from "../lib/api/clientFetch";
import { runWeeklyReviewSelfCheck } from "../lib/dailyLoop/weeklyReview";
import { runTradeFillSelfCheck } from "../services/trade/logTradeFill";
import { runSyncKiteBrokerFillSelfCheck } from "../services/trade/syncKiteBrokerFill";

runCapitalProjectionSelfCheck();
runCapitalFinalStateSelfCheck();
runCapitalDecisionLockSelfCheck();
runCapitalMarginSelfCheck();
runTodaySurfaceSelfCheck();
runZerodhaFundsSelfCheck();
runCommitmentSelfCheck();
runDisciplineHistoryMergeSelfCheck();
runTradingDateSelfCheck();
runDisciplineStatusSelfCheck();
runBrokerStepStateSelfCheck();
runMarketSessionSelfCheck();
runTradeExecutionErrorSelfCheck();
runWeeklyReviewSelfCheck();
runTradeFillSelfCheck();
runSyncKiteBrokerFillSelfCheck();
