import type { MonthlyDoctorViewModel } from "@/types/monthlyDoctor";
import type { MonthlyTrendLine } from "@/services/review/buildMonthlyTrends";

export function exportMonthlyDoctorMarkdown(
  doctor: MonthlyDoctorViewModel,
  trends: MonthlyTrendLine[] = [],
): string {
  const lines: string[] = [
    `# APEX Monthly Portfolio Doctor`,
    ``,
    `- **Month:** ${doctor.month_label}`,
    `- **Headline:** ${doctor.headline}`,
    ``,
    `## Summary`,
    doctor.summary,
    ``,
  ];

  if (doctor.concentration_warning) {
    lines.push(`## Concentration`, doctor.concentration_warning, ``);
  }

  lines.push(
    `- **Sacred core:** ${doctor.sacred_core_ok ? "Within bounds" : "Review concentration"}`,
    ``,
  );

  if (trends.length > 0) {
    lines.push(`## Month-over-month`, ...trends.map((t) => `- ${t.label}: ${t.value}`), ``);
  }

  if (doctor.action_items.length > 0) {
    lines.push(`## Action items`, ...doctor.action_items.map((item) => `- ${item}`), ``);
  }

  lines.push(`---`, `Generated by APEX · ${doctor.built_at}`);

  return lines.join("\n");
}

export function downloadMonthlyDoctorMarkdown(
  doctor: MonthlyDoctorViewModel,
  trends: MonthlyTrendLine[] = [],
): void {
  const markdown = exportMonthlyDoctorMarkdown(doctor, trends);
  const blob = new Blob([markdown], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = `apex-monthly-doctor-${doctor.month_label.replace(/\s+/g, "-").toLowerCase()}.md`;
  anchor.click();
  URL.revokeObjectURL(url);
}

export function runMonthlyDoctorExportSelfCheck(): void {
  const markdown = exportMonthlyDoctorMarkdown({
    built_at: new Date().toISOString(),
    month_label: "August 2026",
    headline: "Steady",
    summary: "Test",
    concentration_warning: null,
    sacred_core_ok: true,
    allocation: null,
    health: [],
    action_items: ["Research RELIANCE"],
    trends: [],
  });

  if (!markdown.includes("Monthly Portfolio Doctor")) {
    throw new Error("Monthly doctor export self-check failed");
  }
}
