import type { DecisionReceiptRow } from "@/services/receipts/persistReceipt";
import {
  parseReceiptSnapshot,
  quoteReceiptVerdict,
} from "@/services/receipts/snapshot";

export function exportReceiptMarkdown(receipt: DecisionReceiptRow): string {
  const snapshot = parseReceiptSnapshot(receipt.brief_snapshot);
  const brief = snapshot.brief;
  const quoted = quoteReceiptVerdict(snapshot);
  const lines: string[] = [
    `# APEX Decision Receipt`,
    ``,
    `- **Date:** ${receipt.receipt_date}`,
    `- **Symbol:** ${receipt.symbol}`,
    `- **Kind:** ${receipt.execution_kind}`,
    `- **Verdict:** ${quoted.source === "artifact" ? quoted.verdict : receipt.verdict_word ?? "—"}`,
    ``,
    `## Headline`,
    receipt.headline ?? "—",
    ``,
    `## Subline`,
    receipt.subline ?? "—",
    ``,
  ];

  if (receipt.order_id && !receipt.order_id.startsWith("discipline:")) {
    lines.push(
      `## Broker fill`,
      `- Order: ${receipt.order_id}`,
      `- Side: ${receipt.fill_side ?? "—"}`,
      `- Qty: ${receipt.fill_quantity ?? "—"}`,
      `- Price: ${receipt.fill_price ?? "—"}`,
      ``,
    );
  }

  if (typeof receipt.trust_score === "number") {
    lines.push(`- **Trust score:** ${receipt.trust_score}/100`);
  }

  if (typeof receipt.trust_delta === "number") {
    lines.push(`- **Trust delta:** ${receipt.trust_delta}`);
  }

  lines.push(``);

  if (quoted.source === "artifact") {
    lines.push(
      `## Frozen decision`,
      `- Verdict: ${quoted.verdict}`,
      `- Reason: ${quoted.reason}`,
      `- Decision id: ${snapshot.artifact?.decision_id ?? "—"}`,
      ``,
    );
  }

  if (brief) {
    lines.push(
      `## Morning brief snapshot`,
      `- Verdict: ${brief.decision.verdict_display}`,
      `- Reason: ${brief.decision.reason}`,
      `- Trust: ${brief.trust.trust_message}`,
      ``,
    );

    if (brief.evidence.key_reasons.length > 0) {
      lines.push(`### Key reasons`, ...brief.evidence.key_reasons.map((r) => `- ${r}`), ``);
    }
  }

  lines.push(`---`, `Generated by APEX · ${receipt.created_at}`);

  return lines.join("\n");
}

export function downloadReceiptMarkdown(receipt: DecisionReceiptRow): void {
  const markdown = exportReceiptMarkdown(receipt);
  const blob = new Blob([markdown], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = `apex-receipt-${receipt.receipt_date}-${receipt.symbol}.md`;
  anchor.click();
  URL.revokeObjectURL(url);
}

export function runReceiptExportSelfCheck(): void {
  const markdown = exportReceiptMarkdown({
    id: "test",
    receipt_date: "2026-08-11",
    symbol: "RELIANCE",
    execution_kind: "WAIT",
    verdict_word: "WAIT",
    headline: "Waited",
    subline: "No trade",
    trust_score: 70,
    trust_delta: 1,
    order_id: null,
    fill_side: null,
    fill_quantity: null,
    fill_price: null,
    fill_amount: null,
    brief_snapshot: null,
    dismissed_at: null,
    created_at: new Date().toISOString(),
  });

  if (!markdown.includes("RELIANCE")) {
    throw new Error("Receipt export self-check failed: missing symbol");
  }
}
