"""Decision Engine — canonical investment verdict layer (Migration Step 3)."""

from analyzer.decision_engine.engine import DecisionEngine, default_decision_engine
from analyzer.decision_engine.factory import DecisionFactory
from analyzer.decision_engine.history import (
    ImmutableDecisionError,
    decision_store_path,
    fetch_decision,
    fetch_decisions_for_subject,
    init_decision_store,
    save_decision,
)
from analyzer.decision_engine.migration import (
    attach_decision_to_advice,
    attach_decision_to_alpha_report,
    attach_decision_to_mis_advisory,
    attach_decision_to_synthesis,
    capital_constraints_from_prefs,
    decide_from_packet,
    evidence_items_from_advisor_signals,
    evidence_items_from_mis_signals,
    legacy_advisor_action,
    legacy_alpha_recommendation,
    legacy_buy_decision,
    legacy_mis_headline,
    legacy_mis_verdict,
    legacy_synthesis_verdict,
    market_context_from_timing,
    risk_settings_from_mis,
    user_preferences_from_prefs,
)
from analyzer.decision_engine.models import (
    DECISION_VERSION,
    CapitalConstraints,
    DecisionArtifact,
    DecisionContext,
    DecisionExplainability,
    DecisionRequest,
    DecisionVerdict,
    MarketContext,
    PortfolioState,
    RiskSettings,
    UncertaintyVector,
    UserPreferences,
)
from analyzer.decision_engine.verdict_bridge import (
    attach_decision_to_analysis,
    attach_decision_to_combined,
    attach_decision_to_fundamental,
    attach_decision_to_holding_advice,
    attach_decision_to_horizon,
    attach_decision_to_intraday,
    attach_decision_to_investment_os,
    attach_decision_to_live_chart,
    attach_decision_to_mtf_report,
    attach_decision_to_options_verdict,
    legacy_chart_action,
    legacy_equity_recommendation,
    resolve_verdict,
)
from analyzer.decision_engine.reasoner import DecisionReasoner
from analyzer.decision_engine.rules import MIN_COMPLETENESS_PCT, is_critical_gap
from analyzer.decision_engine.serialization import (
    decision_artifact_from_dict,
    decision_artifact_from_json,
    decision_artifact_to_dict,
    decision_artifact_to_json,
)
from analyzer.decision_engine.serializer import SCHEMA_VERSION
from analyzer.decision_engine.validator import DecisionValidationError, DecisionValidator

__all__ = [
    "DECISION_VERSION",
    "CapitalConstraints",
    "DecisionArtifact",
    "DecisionContext",
    "DecisionEngine",
    "DecisionExplainability",
    "DecisionFactory",
    "DecisionReasoner",
    "DecisionRequest",
    "DecisionValidationError",
    "DecisionValidator",
    "DecisionVerdict",
    "ImmutableDecisionError",
    "MarketContext",
    "MIN_COMPLETENESS_PCT",
    "PortfolioState",
    "RiskSettings",
    "SCHEMA_VERSION",
    "UncertaintyVector",
    "UserPreferences",
    "attach_decision_to_advice",
    "attach_decision_to_alpha_report",
    "attach_decision_to_analysis",
    "attach_decision_to_combined",
    "attach_decision_to_fundamental",
    "attach_decision_to_holding_advice",
    "attach_decision_to_horizon",
    "attach_decision_to_intraday",
    "attach_decision_to_investment_os",
    "attach_decision_to_live_chart",
    "attach_decision_to_mis_advisory",
    "attach_decision_to_mtf_report",
    "attach_decision_to_options_verdict",
    "attach_decision_to_synthesis",
    "capital_constraints_from_prefs",
    "decide_from_packet",
    "decision_artifact_from_dict",
    "decision_artifact_from_json",
    "decision_artifact_to_dict",
    "decision_artifact_to_json",
    "decision_store_path",
    "default_decision_engine",
    "evidence_items_from_advisor_signals",
    "evidence_items_from_mis_signals",
    "fetch_decision",
    "fetch_decisions_for_subject",
    "init_decision_store",
    "is_critical_gap",
    "legacy_advisor_action",
    "legacy_alpha_recommendation",
    "legacy_buy_decision",
    "legacy_chart_action",
    "legacy_equity_recommendation",
    "legacy_mis_headline",
    "legacy_mis_verdict",
    "legacy_synthesis_verdict",
    "market_context_from_timing",
    "resolve_verdict",
    "risk_settings_from_mis",
    "save_decision",
    "user_preferences_from_prefs",
]
