"""Export investigation results as shareable markdown."""

from __future__ import annotations

from datetime import datetime, timezone

from investigator.rca import RCAResult
from investigator.timeline import Timeline


def _status_icon(status: str) -> str:
    return {"healthy": "OK", "warning": "WARN", "failed": "FAIL", "unknown": "?"}.get(status, "?")


def build_markdown_report(
    *,
    interaction_id: str,
    symptom: str,
    timeline: Timeline,
    rca: RCAResult,
) -> str:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines = [
        "# Interaction Investigation Report",
        "",
        f"**Generated:** {now}  ",
        f"**Interaction ID:** {interaction_id or 'not provided'}  ",
        f"**Symptom:** {symptom or 'not provided'}  ",
        f"**Analysis method:** {rca.method}  ",
        "",
        "## Executive summary",
        "",
    ]

    if rca.primary_cause:
        p = rca.primary_cause
        lines.extend(
            [
                f"**Likely root cause:** {p.label} ({p.confidence} confidence)  ",
                f"{p.summary}",
                "",
            ]
        )
        if p.evidence:
            lines.append("**Evidence:**")
            for item in p.evidence:
                lines.append(f"- `{item}`")
            lines.append("")

    lines.extend(["## Journey timeline", "", "| Stage | Status | Events | Errors | Notes |", "|---|---|---:|---:|---|"])
    for stage in timeline.stages:
        note = stage.highlights[0][:80] if stage.highlights else "—"
        if stage.event_count == 0 and stage.status == "unknown":
            note = "no matching log lines"
        lines.append(
            f"| {stage.label} | {_status_icon(stage.status)} | {stage.event_count} | "
            f"{stage.error_count} | {note} |"
        )
    lines.append("")

    lines.extend(["## Hypotheses (ranked)", ""])
    for idx, h in enumerate(rca.hypotheses, start=1):
        lines.append(f"{idx}. **{h.label}** — {h.confidence} confidence")
        lines.append(f"   {h.summary}")
        for ev in h.evidence[:2]:
            lines.append(f"   - `{ev}`")
        lines.append("")

    lines.extend(["## Recommended actions", ""])
    for action in rca.recommended_actions:
        lines.append(f"- {action}")
    lines.append("")

    lines.extend(["## Customer update (draft)", "", rca.customer_update_draft, ""])
    lines.extend(
        [
            "---",
            "*Generated by Interaction Investigator — vendor-agnostic log analysis.*",
        ]
    )
    return "\n".join(lines)
