import type { InvestmentThesisRow } from "@/types/investmentThesis";

export function exportInvestmentBookMarkdown(theses: InvestmentThesisRow[]): string {
  const lines: string[] = [
    "# APEX Investment Book",
    "",
    `Symbols documented: ${theses.length}`,
    "",
  ];

  if (theses.length === 0) {
    lines.push("_No theses saved yet. Add them from Research → Thesis._", "");
  } else {
    for (const row of theses) {
      lines.push(
        `## ${row.symbol}`,
        "",
        `Updated · ${new Date(row.updated_at).toLocaleDateString("en-IN", { timeZone: "Asia/Kolkata" })}`,
        "",
        "### Thesis",
        row.thesis,
        "",
      );

      if (row.invalidation?.trim()) {
        lines.push("### Invalidation", row.invalidation.trim(), "");
      }

      lines.push("---", "");
    }
  }

  lines.push(`Generated by APEX · ${new Date().toISOString()}`);

  return lines.join("\n");
}

export function runInvestmentBookExportSelfCheck(): void {
  const markdown = exportInvestmentBookMarkdown([
    {
      id: "1",
      symbol: "INFY",
      thesis: "Quality compounder with steady cash flows.",
      invalidation: "Break below 200-week trend.",
      updated_at: new Date().toISOString(),
    },
  ]);

  if (!markdown.includes("Investment Book") || !markdown.includes("INFY")) {
    throw new Error("Investment book export self-check failed");
  }
}
